import Header from "@/components/ui/Header";
import "./globals.css";
import SideDrawer from "@/components/ui/SideDrawer";
import { AppProvider } from "@/Context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark">
        <AppProvider>
          <Header />
            {children}
        </AppProvider>
      </body>
    </html>
  );
}
