import Header from "@/components/ui/Header";
import "./globals.css";
import SideDrawer from "@/components/ui/SideDrawer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark">
        <Header />
          <div className=" h-[calc(100vh-80px)] grid grid-cols-6">
            <div className=" h-full col-span-1" >
              <SideDrawer />
            </div>
            <div className="h-full col-span-5 " >
               {children}
            </div>
          </div>
          
      </body>
    </html>
  );
}
